window.OnScroll=window.OnScroll||{};window.OnScroll.instances=window.OnScroll.instances||[];
window.OnScroll.Container=function(e,k){var B=function(){return function(w){function g(){for(var b=h.length;b--;){var a=x(h[b][0].id);if(a.sticky&&h[b][2]){var c=h[b],d=c,f=a;n=n||k;t=t||n.body;u=u||k.documentElement;f.adContainer=f.adContainer||d[0].getElementsByTagName("div")[0];f.marginTop=f.marginTop||15;f.constraintMargin=f.constraintMargin||15;var d=a.marginTop,C=c[0].getBoundingClientRect(),p=a.adContainer.getBoundingClientRect(),f=C.top,p=p.bottom-p.top;if(f)if(f<=d){if(a.stickyMode||(a.original=
D(c,a,p),a.stickyMode=!0),a.footerHeight||a.constraintWrapper||a.constraintWrapperId||a.constraintFooter||a.constraintFooterId){var l,g,f=d,d=p,p=Math.max(t.scrollHeight,t.offsetHeight,u.clientHeight,u.scrollHeight,u.offsetHeight);g="CSS1Compat"===(k.compatMode||"");g="undefined"!==typeof e.pageXOffset?e.pageYOffset:g?k.documentElement.scrollTop:k.body.scrollTop;var m;l=void 0;var q=a;m=q.conEl;var r="top";if(q.constraintWrapper||q.constraintWrapperId)r="bottom";if(!m){if(m=q.constraintWrapperId||
q.constraintFooterId)l=n.getElementById(m);if(m=q.constraintFooter||q.constraintWrapper)l=n.querySelector(m);m=l}m?(q.conEl=m,l=m.getBoundingClientRect()[r]):l=!1;l=!1!==l?p-l-g+a.constraintMargin:a.footerHeight;g+d+f>p-l?(c=l,f=a.adContainer.style||{},f.position="relative",f.top=p-C.top-g-c-d+"px",a.footerMode=!0):(D(c,a,d),a.footerMode=!1)}}else a.stickyMode&&(c=a,d=c.adContainer.style||{},d.position=c.original.position,d.top=c.original.top,a.stickyMode=!1)}E(h[b][0])&&(a=h[b],a[2]||F.apply(googletag,
a[1]),a[2]=!0)}}function G(b){for(var a={num:0},c=0;c<b.length;++c)if(0===b[c].name.indexOf("data-onscroll-")){var d=b[c].name.substr(14).replace(/[-_]([a-z])/g,function(a){return a[1].toUpperCase()});a[d]=r(b[c].value);a.num++}return a}function r(b){return"true"===b?!0:"false"===b?!1:isNaN(b)?b:1*b}function E(b){b=b.getBoundingClientRect();var a=e.innerWidth||k.documentElement.clientWidth||t.clientWidth,c=e.innerHeight||k.documentElement.clientHeight||t.clientHeight;return.5<=(Math.max(0,Math.min(b.right+
1,a))-Math.max(0,Math.min(b.left-1,a)))*(Math.max(0,Math.min(b.bottom+1,c))-Math.max(0,Math.min(b.top-1,c)))/((b.right-b.left)*(b.bottom-b.top))}function y(b,a,c){b.addEventListener?b.addEventListener(a,c,!1):b.attachEvent("on"+a,c)}function x(b){for(var a=v.length,c;a--;)if(v[a].id===b){c=v[a];break}return c||!1}function D(b,a,c){var d=a.adContainer.style||{},f={position:d.position,top:d.top};d.position="fixed";d.top=a.marginTop+"px";c&&(b[0].style.height=c+"px");return f}if(!googletag.ONSCROLL){googletag.ONSCROLL=
!0;w=w||{};var v=w.placements||[{id:"os-placeholder - id"}];googletag.pubads().enableSingleRequest=function(){return this};var F=googletag.display,B=googletag.defineSlot,z={},h=[],n=k,u=n.documentElement,t=k.body,A=!0;googletag.display=function(){var b=arguments[0],a=n.getElementById(b);if(a){var c=b,d=G(a.attributes),f=x(c);d.timeInView=d.refreshCounter=0;if(f)for(var e in d)d.hasOwnProperty(e)&&(f[e]=d[e]);else d.num&&(d.id=c,v.push(d));c=arguments;e=a.id;d=n.getElementById(e);f=n.createElement("div");
e+="-wrapper";f.id=e;d.appendChild(f);c[0]=e}if(0===v.length)return h.push([a,arguments,!1]),g(),this;x(b)?(h.push([a,arguments,!1]),g()):F.apply(googletag,arguments);return this};googletag.defineSlot=function(){var b=arguments.length-1,a=arguments[b]+"-wrapper";arguments[b]=a;z[a]=B.apply(googletag,arguments);return z[a]};y(e,"scroll",g);y(e,"load",g);y(e,"focus",function(){A=!0});y(e,"blur",function(){A=!1});setInterval(function(){if(A)for(var b=h.length,a,c,d;b--;)h[b][2]&&(a=x(h[b][0].id),c=z[h[b][1][0]],
d=h[b][0],d=d.getElementsByTagName("div")[0],E(d)&&(a.timeInView++,0<a.timeInView&&0===a.timeInView%a.refreshInterval&&(a.refreshCounter++,googletag.pubads().refresh([c]))))},1E3)}}}();e.OnScroll.instances.push(B);return function(w){setTimeout(function(){if(!e.OnScroll.forensiqLoaded){var g="//c.securepaths.com/js/implement.js?org=Pe5usPa6etEnafrupEsw&s="+(new Date).getTime()+"&p="+e.location.host+"&rt=click&sl=1",r=k.createElement("script");r.id="forensiq";r.src=g;k.body.appendChild(r);e.OnScroll.forensiqLoaded=
!0}},0);var g=e.OnScroll.instances.pop();if("function"==typeof g)return g.apply(g,arguments)}}(window,document);